apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanet-backend
  labels:
    app: vanet-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vanet-backend
  template:
    metadata:
      labels:
        app: vanet-backend
    spec:
      containers:
        - name: vanet-backend
          image: athiya4syed/vanet-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/roadsafety_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vanet-secrets
                  key: db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vanet-secrets
                  key: db-password
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/vanet/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/vanet/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanet-postgres
  labels:
    app: vanet-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vanet-postgres
  template:
    metadata:
      labels:
        app: vanet-postgres
    spec:
      containers:
        - name: postgres
          image: postgis/postgis:16-3.4
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: roadsafety_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: vanet-secrets
                  key: db-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vanet-secrets
                  key: db-password
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi